#!/bin/sh

# Padding
bspc config top_padding 50
bspc config bottom_padding 30
bspc config left_padding 30
bspc config right_padding 30

# Borders and gaps
bspc config border_width 1
bspc config window_gap 70
bspc config borderless_monocle false
bspc config gapless_monocle false

# Border colors
bspc config normal_border_color "#222222"
bspc config active_border_color "#aaaaaa"
bspc config focused_border_color "#cccccc"

# Multihead behavior
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Focusing behavior
bspc config focus_follows_pointer false
bspc config history_aware_focus true
bspc config click_to_focus true

# Set up displays
bspc monitor --reset-desktops 1
bspc monitor --add-desktops 2
bspc monitor --add-desktops 3
bspc monitor --add-desktops 4

# Misc
bspc config auto_cancel true
bspc config automatic_scheme spiral
bspc config initial_polarity first_child
bspc config split_ratio 0.50

bspc rule -a *:sun-awt-X11-XFramePeer state=floating
bspc rule -a "Galculator" state=floating
bspc rule -a "Lxappearance" state=floating
bspc rule -a "Nightly" state=tiled
bspc rule -a "qt5ct" state=floating
bspc rule -a "Wine" state=floating
bspc rule -a "zoom" state=floating
bspc rule -a mpv state=floating
bspc rule -a tint2 floating=on manage=off layer=below
