alias ..='cd ..'
alias ...='cd ../..'

alias checkip='curl -s checkip.dyndns.org | grep -Eo "[0-9\.]+"'
alias largest="find . -printf '%s %p\n' | sort -nr | head"
alias logout='pkill -KILL -u $(whoami)'
alias ls='ls --color=auto -a'
alias mv='mv -iv'
alias rm='rm -Iv --one-file-system'
alias cp='cp -iv'
alias tar='tar -v'
alias lsize='du -sh .[!.]* ./* | sort -h | tail'
alias install='sudo apt-get install'
alias uninstall='sudo apt-get purge'
alias update='sudo apt-get update ; sudo apt-get dist-upgrade'
alias finda='sudo find / -name'
alias find='sudo find'
alias sudo='sudo '
alias backup='sudo tar -cf "/media/removable/mogi/chieri.tar" --exclude-tag-all=exclude "/home/chieri"'
# alias hdmi='xrandr --output HDMI2 --mode 1920x1080'
alias hdmi='xrandr --output HDMI-1 --mode 1280x720 --right-of eDP-1 --scale 1x1 --set audio force-dvi'
alias pipes='pipes -r 0 -f 50 -s 15 -t 2'
alias screenfetch='neofetch'
alias np='notify-send "$(mpc)"'
alias todo='nano ~/todo.txt'
alias status='notify-send -t 30000 "$(fortune)" && notify-send -t 30000 "todo:" "$(cat ~/todo.txt)"'
alias pipesx='pipesX -r 0 -f 100'
alias pipesX='pipesX -r 0 -f 100'
alias git-add='git add -A'
alias git-push='git push origin master'
alias git-undo='git reset --soft HEAD~1'
alias dict='dict -d wn'
alias deb='sudo dpkg -R --install .'
alias cmatrix='cmatrix -b'
alias mogi='sudo mount -o remount,exec /media/removable/mogi'
alias texpack='tlmgr install'
alias reloadt='xrdb -merge /home/chieri/.config/urxvt/Xresources'
alias lg3d='wmname LG3D'
alias clean='sudo deborphan --guess-all | sudo xargs apt-get -y remove --purge'
alias KINGSTON='sudo umount /media/removable/KINGSTON'
alias stretch='echo "sudo apt-get install [name]/stretch"'
alias awoo='ssh horo@awoo'
alias retropie='ssh pi@retropie'
alias openelec='sshpass -p 'openelec' ssh root@openelec'
alias twitchchat='irssi --connect=twitch'
alias detach='sudo udisks --detach'
alias permit='sudo chmod 755'
alias matlabc='matlab -nojvmq'
alias gz='tar -zxvf'
alias font='sudo fc-cache -f -v'
alias packages='dpigs'
alias horo='sudo mount -o remount,exec /media/removable/horo'
alias matl='/media/removable/horo/bin/MATLAB/bin/matlab -nosoftwareopengl'
alias python='python3'
alias lsl='ls --color=auto -al'
alias emacs='emacs -nw'
alias winpid='xprop _NET_WM_PID'
alias winclass='xprop | grep WM_CLASS'
alias r='R'
alias dirstat='sudo ncdu -rx /'
alias r-a-dio='nohup mpv --no-ytdl https://stream.r-a-d.io/main.mp3 &>/dev/null &'

function html2pdf() { wkhtmltopdf --zoom 1.25 -s Letter "$@".html "$@.pdf"; }
function stream() { streamlink --player mpv "$@" best; }
function twitch() { streamlink --player mpv twitch.tv/"$@" best & irssi --connect=twitch; }
function git-commit() { git commit -m "[$(date +"%D %H:%M")] $*"; }
