#!/bin/sh

# Padding
bspc config top_padding 40
bspc config bottom_padding 20
bspc config left_padding 20
bspc config right_padding 20

# Borders and gaps
bspc config border_width 1
bspc config window_gap 40
bspc config borderless_monocle false
bspc config gapless_monocle false

# Border colors
bspc config normal_border_color "#222222"
bspc config active_border_color "#aaaaaa"
bspc config focused_border_color "#cccccc"

# Multihead behavior
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Focusing behavior
bspc config focus_follows_pointer false
bspc config history_aware_focus true
bspc config click_to_focus true

# Set up displays
bspc monitor --reset-desktops 1
bspc monitor --add-desktops 2
bspc monitor --add-desktops 3
bspc monitor --add-desktops 4

# Misc
bspc config split_ratio 0.50
bspc config auto_cancel true
bspc config initial_polarity first_child

bspc rule -a *:sun-awt-X11-XFramePeer state=floating
bspc rule -a chrome_app_list floating=on
bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a Electron.. state=floating
bspc rule -a Galculator floating=on
bspc rule -a gbacklight floating=on
bspc rule -a lxappearance floating=on
bspc rule -a Matplotlib state=floating
bspc rule -a mpv state=floating layer=above
bspc rule -a oblogout floating=on fullscreen=on
bspc rule -a Redshiftgui.elf floating=on
bspc rule -a Screenkey manage=off
bspc rule -a stepmania state=floating
bspc rule -a tint2 floating=on manage=off layer=below
bspc rule -a Tk state=floating
bspc rule -a Wicd-client.py floating=on
